# Generated by Django 4.0.1 on 2022-02-03 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('hierarchy', models.CharField(blank=True, max_length=500)),
                ('is_child_a_category', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.CharField(blank=True, max_length=200)),
                ('hierarchy', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('slug', models.SlugField(blank=True)),
                ('article', models.CharField(blank=True, max_length=30)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weight_measure_unit', models.CharField(default='кг', max_length=20)),
                ('price', models.FloatField(blank=True, default=0)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True, null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.client')),
                ('items', models.ManyToManyField(blank=True, to='api.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/cart_files/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.order')),
            ],
        ),
    ]
