# Generated by Django 4.0.1 on 2022-02-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_parent_category_parent_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent_string',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_child_a_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
