# Generated by Django 4.0.1 on 2022-04-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
