# Generated by Django 4.0.1 on 2022-04-10 06:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_parent_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to=api.models.get_upload_path),
        ),
    ]
