# Generated by Django 4.0.1 on 2022-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to='items'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
