# Generated by Django 4.0.1 on 2022-02-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_item_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='market.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_string',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
